service: ses-management-service

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-bundle

package:
  patterns:
    - node_modules/aws-sdk/**

provider:
  name: aws
  memorySize: 128
  region: ${opt:region, 'eu-central-1'}
  versionFunctions: false
  runtime: nodejs14.x
  stackName: ${self:service}-stack
  deploymentBucket:
    name: ${param:bucket}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: [ lambda:InvokeFunction ]
          Resource: "*"
        - Effect: Allow
          Action: [ ses:* ]
          Resource: "*"
        - Effect: Allow
          Action: [ logs:* ]
          Resource: "*"
  environment:
    REGION: ${self:provider.region}
    SENDER: ${param:sender}
    DESTINATION: ${param:destination}

custom:
  sesNotificationsTopicName: ses-business-support
  sesNotificationsTopicArn:
    Fn::Join:
      - ""
      - - "arn:aws:sns:"
        - Ref: "AWS::Region"
        - ":"
        - Ref: "AWS::AccountId"
        - ":"
        - ${self:custom.sesNotificationsTopicName}
  bundle:
    forceExclude:
      - aws-sdk
    excludeFiles:
      - "deploy.sh"

functions:
  send-notification-handler:
    handler: index.sendNotificationHandler
    events:
      - sns:
          arn: ${self:custom.sesNotificationsTopicArn}
          topicName: ${self:custom.sesNotificationsTopicName}
  info:
    handler: index.handler
    events:
      - http:
          path: /info
          method: get
          cors:
            headers:
              - '*'
            origin:
              - '*'
  identities:
    handler: index.identityHandler
    events:
      - http:
          path: /identities
          method: get
          cors:
            headers:
              - '*'
            origin:
              - '*'
      - http:
          path: /identities/{identity}
          method: post
          cors:
            headers:
              - '*'
            origin:
              - '*'
      - http:
          path: /identities/{identity}
          method: delete
          cors:
            headers:
              - '*'
            origin:
              - '*'